<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HarmonyWeaver.Tests.Patches</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Harmony\Lib.Harmony\Lib.Harmony.csproj" />
        <ProjectReference Include="..\PreludeLib.Tests.Examples\PreludeLib.Tests.Examples.csproj" />
        <ProjectReference Include="..\PreludeLib.Tests.Utils\PreludeLib.Tests.Utils.csproj" />
    </ItemGroup>

</Project>
